# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlB9-mFt4Qr65Gx2_-d8lclEGMwnP8cN
"""

print("hello world")